# Generated by Django 3.2 on 2021-04-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20210423_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': ('Сообщение',), 'verbose_name_plural': ('Сообщения',)},
        ),
    ]
